name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  check-x86-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - run:
          nix build .#packages.x86_64-linux.fluxer 
  auto-merge:
    needs: [check-x86-linux]
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automated')
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
